In [27]:
import os
import torch
import torch.utils.data as data
import torch
import torchvision.transforms as transforms
import random
from PIL import Image, ImageOps
import numpy as np

In [28]:
left_dic = "/data/users/mzy/stereoMaching/PSMNet/training/image_2/000000_10.png"
right_dic = "/data/users/mzy/stereoMaching/PSMNet/training/image_3/000000_10.png"

In [29]:
leftimage = Image.open(left_dic).convert("RGB")
rightimage = Image.open(right_dic).convert("RGB")

In [30]:
disp_dic = "/data/users/mzy/stereoMaching/PSMNet/training/disp_occ_0/000000_10.png"
disp = Image.open(disp_dic)

In [31]:
from utils import preprocess

In [32]:
w, h = leftimage.size
th, tw = 256, 512
 
x1 = random.randint(0, w - tw)
y1 = random.randint(0, h - th)

leftimg = leftimage.crop((x1, y1, x1 + tw, y1 + th))
rightimg = rightimage.crop((x1, y1, x1 + tw, y1 + th))

In [33]:
dataL = np.ascontiguousarray(disp,dtype=np.float32)/256
dataL = dataL[y1:y1 + th, x1:x1 + tw]

In [34]:
left_img = np.array(leftimg)
right_img = np.array(rightimg)

In [35]:
#import torchvision.transforms as transforms
#left_img = transforms.ToTensor()(leftimg)
#right_img = transforms.ToTensor()(rightimg)

In [36]:
left_img.shape

(256, 512, 3)

In [37]:
from torch.autograd import Variable
imgL   = Variable(torch.FloatTensor(left_img))
imgR   = Variable(torch.FloatTensor(right_img))   
disp_L = Variable(torch.FloatTensor(dataL))

In [38]:
imgL.shape

torch.Size([256, 512, 3])

In [39]:
imgL.shape

torch.Size([256, 512, 3])

In [40]:
disp_L.shape

torch.Size([256, 512])

In [63]:
imgL[255,460,:]

tensor([56., 66., 78.])

In [64]:
imgR[208,460,:]

tensor([53., 63., 82.])

In [43]:
print(np.where(disp_L>0))

(array([ 75,  75,  75, ..., 255, 255, 255]), array([ 12,  13,  17, ..., 454, 457, 460]))


In [59]:
disp_L[255,460]

tensor(47.1914)

In [45]:
w,h,c = imgL.shape

In [46]:
print(w,h,c)

(256, 512, 3)


In [22]:
imgL.size()

torch.Size([256, 512])

In [75]:
tmp = torch.FloatTensor(256,512,3).zero_()
wraped_left = Variable(tmp)

In [81]:
import time
st = time.time()
for x in range(w):
    for y in range(h):
        x_n = x+disp_L[x][y]
        x_n = int(x_n.item())
        if(x_n<w):
            tmp[x_n,y,:] = imgL[x,y,:]
print (time.time() - st) / 3600

0.000793578889635


In [ ]:
mask = 