In [4]:
import torch
import numpy as np

In [5]:
n = np.arange(0, 30, 2)# start at 0 count up by 2, stop before 30
n = n.reshape(3, 5) # reshape array to be 3x5

In [6]:
correct = n > 10

In [7]:
correct

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [8]:
torch.sum(correct)

TypeError: sum(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [10]:
torch.tensor(n)

tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28]])

In [11]:
correct = n>10

In [12]:
correct

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [13]:
torch.sum(correct)

TypeError: sum(): argument 'input' (position 1) must be Tensor, not numpy.ndarray